In [18]:
import numpy as np
import torch
import os,sys

In [19]:
a = np.load("DB2.npy",allow_pickle=True).item()

In [20]:
a.keys()

dict_keys(['latents', 'shapes', 'performances'])

In [21]:
a["latents"].shape , a["shapes"].shape , a["performances"].shape

((1000, 2, 192), (1000, 192, 2), (1000, 3))

In [22]:
p = a["performances"]
print(len(np.unique(p[:,2])))
# for sample in p:
#     print(sample)
#     print(type(sample[2]))
indices = np.argsort(p[:,2],axis=0)
for index in indices:
    print(p[index])

200
[-1000.  1000.     0.]
[0.213041 0.009161 0.      ]
[0.208951 0.013946 0.      ]
[0.069368 0.009036 0.      ]
[-1000.  1000.     0.]
[0.093191 0.01141  1.      ]
[0.245418 0.01589  1.      ]
[0.116986 0.011032 1.      ]
[-1000.  1000.     1.]
[-1000.  1000.     1.]
[0.068492 0.011088 2.      ]
[-1000.  1000.     2.]
[-0.023645  0.007527  2.      ]
[0.102389 0.008817 2.      ]
[-1000.  1000.     2.]
[-1000.  1000.     3.]
[0.028234 0.009235 3.      ]
[-1000.  1000.     3.]
[0.059051 0.00881  3.      ]
[0.208327 0.01011  3.      ]
[0.071635 0.008684 4.      ]
[0.12362  0.009219 4.      ]
[0.199315 0.007728 4.      ]
[-1000.  1000.     4.]
[-1000.  1000.     4.]
[0.159076 0.010871 5.      ]
[0.195844 0.009361 5.      ]
[0.155901 0.014797 5.      ]
[-1000.  1000.     5.]
[0.247992 0.012104 5.      ]
[-1000.  1000.     6.]
[-1000.  1000.     6.]
[0.098891 0.013321 6.      ]
[0.230239 0.008662 6.      ]
[-1000.  1000.     6.]
[0.068056 0.0093   7.      ]
[0.069543 0.008477 7.      ]
[0.2

In [23]:
cl = 6.116e-03
cd = 7.981e-03
for sample in p:
    if sample[0] == cl and sample[1] == cd:
        print(sample[2])

109.0
